// Packs src/ into a single self-contained HTML file (soundwave-bounce.html).
// CSS files are inlined in the order below; JS files in src/js are
// concatenated by filename into one <script type="module">.
// Usage: node scripts/build.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'src');
const out = join(root, 'soundwave-bounce.html');

const CSS_ORDER = ['theme.css', 'layout.css', 'components.css'];

const read = (p) => readFileSync(p, 'utf8').trimEnd();
const indent = (text, pad) => text.split('\n').map((l) => (l ? pad + l : l)).join('\n');

const css = CSS_ORDER.map((f) => `/* ── ${f} ── */\n` + read(join(src, 'styles', f))).join('\n\n');
const js = readdirSync(join(src, 'js'))
  .filter((f) => f.endsWith('.js'))
  .sort()
  .map((f) => `// ── ${f} ──\n` + read(join(src, 'js', f)))
  .join('\n\n');

let html = read(join(src, 'index.html'));
html = html.replace('<!-- @inline-css -->', () => `<style>\n${indent(css, '    ')}\n  </style>`);
html = html.replace('<!-- @inline-js -->', () => `<script type="module">\n${indent(js, '    ')}\n  </script>`);

// Banner goes after the doctype; anything before it would trigger quirks mode.
html = html.replace('<!DOCTYPE html>', '<!DOCTYPE html>\n<!-- Generated by scripts/build.mjs from src/ — edit the sources, not this file. -->');
writeFileSync(out, html + '\n');
console.log(`Wrote ${out} (${(Buffer.byteLength(html) / 1024).toFixed(1)} KB)`);
